---
- hosts: all
  gather_facts: no
  connection: local
  tasks:
  - name: "awx_provision"
    generalovmaksim.awx.awx_provision:
      configuration: "{{ ansible_tower }}"
    register: results

  - name: "Show results"
    debug:
      msg: "{{ results }}"